### ISSUE TITLE
Zapoznanie się z bibliotekami do rozpoznawania mowy i wybór odpowiedniej.

### ISSUE THREAD

**Issue by pvrtykv** [pvrtykv/SpeechTranscription#1]

**Comment by pvrtykv** [comment]
https://realpython.com/python-speech-recognition/ W artykule opisane są pythonowe paczki do rozpoznowania mowy - najprostszym w użyciu wydaje się być pakiet SpeechRecognition

**Comment by JoannaHankus** [comment]
Wybrana biblioteka : Python SpeechRecognition 
Jest to biblioteka, która umożliwia rozpoznawanie mowy, wspiera kilka silników, w tym CMU Sphinx działającego w trybie offline.

Wybrany SRE : CMU Sphinx - technologia Java i Python

Opis tworzenia modelu językowego dla Sphinxa:
https://cmusphinx.github.io/wiki/tutoriallm/

polski model językowy dla Julisa:
http://www.voxforge.org/home/forums/message-boards/general-discussion/polish-speech-models-for-julius
https://sourceforge.net/projects/skrybotdomowy/files/Models/

przykładowy plik modelu językowego dla j. angielskiego : 
http://www.voxforge.org/home/downloads/speech/english/serak-20170326-dvj#47OMsQTSD7UKSBkku0PXwQ
