### ISSUE TITLE
Określenie wymagań funkcjonalnych

### ISSUE THREAD

**Issue by pvrtykv** [pvrtykv/SpeechTranscription#2]

**Comment by pvrtykv** [comment]
Zapis audio sesji, transkrypcja do tekstu, bezpieczne przechowywanie danych, praca offline

**Comment by JoannaHankus** [comment]
- logowanie 
	- zmiana miejsca zapisu plików
	- zapis audio 
	- czy analiza w czasie rzeczywistym? 
	- zapis transkrypcji do pliku tekstowego
	- wylogowanie

**Comment by JoannaHankus** [comment]
Wymagania funkcjonalne
- logowanie 
- zmiana miejsca zapisu plików
- zapis audio 
- zapis transkrypcji do pliku tekstowego
- wylogowanie
