### ISSUE TITLE
Zapoznanie się z dostępnymi rozwiązaniami

### ISSUE THREAD

**Issue by pvrtykv** [pvrtykv/SpeechTranscription#4]
Transkrypcja mowy offline, oszacowanie czasu zbudowania modelu, użycie serwisu online lub rezygnacja z transkrypcji języka polskiego (zamiast tego język angielski).

**Comment by pvrtykv** [comment]
http://www.voxforge.org/home/forums/message-boards/general-discussion/polish-speech-models-for-julius?fbclid=IwAR31Y3d08hSb7HtMnIw3Jc-ZhxmOIq-DGA5VL_a6OgjB-uBHrDdw0JNR33A - polski model językowy dla juliusa

**Comment by JoannaHankus** [comment]
### Julius
Julius to silnik rozpoznawania mowy typu LVCSR (Large vocabulary continuous speech recognition), pracujący w czasie prawie rzeczywistym, działający na różnych systemach operacyjnych (Unix/Windows), wydany na free licencji BSD. Silniki LVCSR opierają się na słowniku (modelu) 50000-100000 słów, mapują słowa na jego fonetyczne brzmienie (zapis za pomocą fonemów) i używają metod statystycznych żeby potwierdzić wystąpienie słowa na podstawie kontekstu zdania. Julius działa w oparciu o dwa modele: 

- statystyczny model języka, czyli rozkład prawdopodobieństwa na sekwencję słów, rozróżnienie znaczenia słów brzmiących podobnie za pomocą kontekstu
- akustyczny model, czyli relację między sygnałem audio a fonemem. Model akustyczny to nagrania plus transkrypcja przemapowane na statystyczną reprezentację dźwięków.
